#!/usr/bin/env bash

readonly TMP_DIR=$(mktemp -d /tmp/clash-attack-sim.XXXXXX)
readonly REPO=git@github.com:jmmk/clash-attack-sim.git
readonly GIT="git -C ${TMP_DIR}"

main() {
  lein clean
  lein cljsbuild once production

  git clone "${REPO}" "${TMP_DIR}"

  $GIT checkout gh-pages
  cp -r resources/public/images "${TMP_DIR}"
  cp target/production/js/clash-attack-sim.js "${TMP_DIR}/javascripts"
  cp resources/public/bower_components/pixi/bin/pixi.js "${TMP_DIR}/javascripts"

  $GIT add -A
  $GIT commit -m "Update to latest build"
  $GIT push origin gh-pages

  rm -rf "${TMP_DIR}"
}

main "${@}"
